import yaml from "js-yaml";
import https from "https";
import fetch from "node-fetch";

export async function convertLockfile(lockV2: string): Promise<string> {
  const lockV2Obj = yaml.load(lockV2);

  const agent = new https.Agent({ keepAlive: true });

  let lockV1 = "";
  lockV1 += "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n"
  lockV1 += "# yarn lockfile v1\n"
  lockV1 += "\n";

  const clausePromises = Object.entries(lockV2Obj as object).map(async ([packageKey, packageData]) => {
    let clause = "";
    if (packageKey === "__metadata") return clause;
    if (/@(?:patch|workspace):/.test(packageKey)) return clause;

    clause += "\n";
    clause += `${convertKey(packageKey)}:\n`;
    if (typeof packageData.version === "string") {
      clause += `  version ${JSON.stringify(packageData.version)}\n`;
    }
    if (typeof packageData.resolution === "string") {
      clause += await convertResolution(packageData.resolution, agent);
    }
    clause += convertDependencies(packageData.dependencies);
  });

  lockV1 += (await Promise.all(clausePromises)).join();

  agent.destroy();

  return lockV1;
}

function convertDependencies(dependencies: unknown): string {
  let output = "";
  if (typeof dependencies !== "object" || dependencies === null) return output;
  output += '  dependencies:\n';

  for (const [depKey, depValue] of Object.entries(dependencies)) {
    output += `    ${escapeIfNeeded(depKey)} ${JSON.stringify(depValue)}\n`;
  }
  return output;
}

async function convertResolution(resolutionV2: string, agent: https.Agent): Promise<string> {
  const [packageName, packageResolution] = resolutionV2.split(/(?!^@)@/, 2);
  const packageBaseName = packageName.split('/').reverse()[0];
  const [protocol, protocolValue] = packageResolution.split(':', 2);
  switch (protocol) {
    case 'npm': {
      const version = protocolValue;
      const resp = await fetch(`https://registry.yarnpkg.com/${packageName}/${version}`, {
        agent,
      });
      if (!resp.ok) {
        throw new Error(`Got ${resp.status} from ${resp.url}`);
      }
      const packageInfo = await resp.json();
      let resolution = "";
      resolution += `  resolution https://registry.yarnpkg.com/${packageName}/-/${packageBaseName}-${version}.tgz#${packageInfo.dist.shasum}\n`;
      resolution += `  integrity ${packageInfo.dist.integrity}\n`;
      return resolution;
    }
    default:
      throw new Error(`unknown package protocol: ${JSON.stringify(protocol)}`);
  }
}

function convertKey(keyV2: string): string {
  return keyV2.split(", ").map((constraintV2) => {
    const constraintV1 = constraintV2.replace("@npm:", "@");
    return escapeIfNeeded(constraintV1);
  }).join(", ");
}

function escapeIfNeeded(val: string): string {
  return /^@| /.test(val) ? JSON.stringify(val) : val;
}
