name: build and test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: yarn build
    - run: yarn tsc
    - run: yarn test
    - run: yarn lint
    - run: yarn fmt:check
